#!/bin/sh

MINCAML_HOME=$(cd "$(dirname "$0")"/../ && pwd)
CP_DIR="$MINCAML_HOME/java/okalm/"
CP_DIR_CLASS="target/classes"
CP="$CP_DIR/java-cup-11b-runtime.jar:$CP_DIR_CLASS/"
cd java/ocamlCompiler
exec java -enableassertions -cp "$CP" okalm.Main ../../$1 $2
cd ../..
