#!/bin/sh

MINCAML_HOME=$(cd "$(dirname "$0")"/../ && pwd)
CP_DIR="$MINCAML_HOME/java/ocamlCompiler/src/main/java/okalm/"
CP="$CP_DIR/java-cup-11b-runtime.jar:$CP_DIR:$MINCAML_HOME/java/ocamlCompiler/target/classes/"
#cd ../../../../java/ocamlCompiler
exec java -enableassertions -cp "$CP" okalm.Main $@
#cd ../..



